/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThiepRouteImport } from './routes/thiep'
import { Route as AnHoiRouteImport } from './routes/an-hoi'
import { Route as IndexRouteImport } from './routes/index'

const ThiepRoute = ThiepRouteImport.update({
  id: '/thiep',
  path: '/thiep',
  getParentRoute: () => rootRouteImport,
} as any)
const AnHoiRoute = AnHoiRouteImport.update({
  id: '/an-hoi',
  path: '/an-hoi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/an-hoi': typeof AnHoiRoute
  '/thiep': typeof ThiepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/an-hoi': typeof AnHoiRoute
  '/thiep': typeof ThiepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/an-hoi': typeof AnHoiRoute
  '/thiep': typeof ThiepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/an-hoi' | '/thiep'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/an-hoi' | '/thiep'
  id: '__root__' | '/' | '/an-hoi' | '/thiep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnHoiRoute: typeof AnHoiRoute
  ThiepRoute: typeof ThiepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thiep': {
      id: '/thiep'
      path: '/thiep'
      fullPath: '/thiep'
      preLoaderRoute: typeof ThiepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/an-hoi': {
      id: '/an-hoi'
      path: '/an-hoi'
      fullPath: '/an-hoi'
      preLoaderRoute: typeof AnHoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnHoiRoute: AnHoiRoute,
  ThiepRoute: ThiepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
