/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DonDau2RouteImport } from './routes/don-dau-2'
import { Route as DonDauRouteImport } from './routes/don-dau'
import { Route as IndexRouteImport } from './routes/index'

const DonDau2Route = DonDau2RouteImport.update({
  id: '/don-dau-2',
  path: '/don-dau-2',
  getParentRoute: () => rootRouteImport,
} as any)
const DonDauRoute = DonDauRouteImport.update({
  id: '/don-dau',
  path: '/don-dau',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/don-dau': typeof DonDauRoute
  '/don-dau-2': typeof DonDau2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/don-dau': typeof DonDauRoute
  '/don-dau-2': typeof DonDau2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/don-dau': typeof DonDauRoute
  '/don-dau-2': typeof DonDau2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/don-dau' | '/don-dau-2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/don-dau' | '/don-dau-2'
  id: '__root__' | '/' | '/don-dau' | '/don-dau-2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonDauRoute: typeof DonDauRoute
  DonDau2Route: typeof DonDau2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/don-dau-2': {
      id: '/don-dau-2'
      path: '/don-dau-2'
      fullPath: '/don-dau-2'
      preLoaderRoute: typeof DonDau2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don-dau': {
      id: '/don-dau'
      path: '/don-dau'
      fullPath: '/don-dau'
      preLoaderRoute: typeof DonDauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonDauRoute: DonDauRoute,
  DonDau2Route: DonDau2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
